### PR TITLE
Versioning

### PR DESCRIPTION
**Pull request by nemchik**
# Pull request

**Purpose**
Describe the problem or feature in addition to a link to the issues.

**Approach**
How does this change address the problem?

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by angrycuban13** [comment]
So far so good.

**Comment by nemchik** [comment]
Same. My testing so far seems to be working fine. I made some additional adjustments just so we don't get users questioning warnings from DS. With these changes the `app.ports.yml` file is completely optional, and a placeholder should not be created in DS (I have removed the existing placeholders).

**Comment by nemchik** [comment]
I'm happy with my testing of this. @angrycuban13 have you had any issues?

**Comment by angrycuban13** [comment]
No issues so far using compose spec. I think we can merge it. 

However, there was that one guy who had the same issue I had but when he ran `docker-compose --version` it started downloading the compose from LSIO.

**Comment by nemchik** [comment]
> No issues so far using compose spec. I think we can merge it.
> 
> However, there was that one guy who had the same issue I had but when he ran `docker-compose --version` it started downloading the compose from LSIO.
> 
> @nemchik

Yeah that's not an issue, it's intentional. These changes increase the minimum required version of `docker` and `docker-compose`. If your system did not already have a compatible version DS would force an update.

**Pull request merged**
