### PR TITLE
Add OpenVPNAS

### LINKED ISSUE #312: OpenVPN-AS
https://hub.docker.com/r/linuxserver/openvpn-as/

This one could be a great add, webgui openvpn server.

### PR DESCRIPTION
**Pull request by nemchik**
## Purpose

This closes #312 

## Approach

Add the required files.

#### Open Questions and Pre-Merge TODOs

- [x] Needs testing.
- [x] Confirm this passes the full generator test.

#### Learning

https://hub.docker.com/r/linuxserver/openvpn-as/

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by sixshooterz** [comment]
Is there a way to make the admin interface (port 943 according to the Docker hub site) accessible through the letsencrypt container? I assume it’s as simple as creating a new proxy-conf file and adding the subdomain to the .env file?

**Comment by sixshooterz** [comment]
Also, what’s the best way to switch branches on a currently running system?

**Comment by nemchik** [comment]
Yes, you can proxy it by copying an existing proxy config and replacing the app name and port in the file.

Testing can be done by
```
cd ~/.docker
git fetch -p
git reset --hard origin/<GITHUB_BRANCH>
git pull
sudo ds -e
sudo ds
```

**Comment by nemchik** [comment]
If someone is able to confirm this works (not just running the container, but actually connecting to the VPN they create with it) I can merge this to master. I may have time to confirm this myself later this week if no one beats me to it.

**Comment by nemchik** [comment]
Yeah there's actually numerous port conflicts across various apps. I used to take it more seriously but came to two conclusions

1. It's not too common that you'll use two apps that want the same port, and
2. If you do happen on that circumstance it's very easy to change a port in DS, and it's an important thing to understand what's happening and how to fix it.

I could put more effort into DS handling it for you, but my hope is that using DS won't be the last efforts people put into learning.

**Comment by sixshooterz** [comment]
Oh, I'm good with that!  I wasn't sure if that was a known thing but figured it probably was.  Changing ports is easy, I found that from day one.

**Pull request merged**
