### PR TITLE
Use hotio/cloudflareddns

### PR DESCRIPTION
**Pull request by nemchik**
**Purpose**
Users on discord expressed having issues with the oznu image some time ago. The oznu image seems to have been updated recently with some potentially breaking changes. @hotio 's image is preferable at this time.

**Approach**
Modify the files to use @hotio image. Remove oznu specific variables and add the variables required for the new image.

**Learning**
https://hub.docker.com/r/hotio/cloudflare-ddns
https://github.com/hotio/docker-cloudflare-ddns

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by dantler** [comment]
Got some support from hotio on this new image.  Here's what worked for me:

1. don't surround any CLOUDFLAREDDNS_* values with quotes in your config file.
2. if using an API token, configure it like this:
- Zone: Zone: Read
- Zone: DNS: Edit
- Include: All Zones

**Comment by nemchik** [comment]
Not sure I follow

**Comment by dantler** [comment]
Just posted my notes for the benefit of others who may struggle migrating from oznu's image to hotio's image.

**Comment by sjdweb** [comment]
Bear in mind this image doesn't have a public source as far as I know:


https://github.com/hotio/docker-cloudflare-ddns/issues/7

**Comment by hotio** [comment]
Don't spread false rumours please...

**Pull request merged**
