### PR TITLE
Added Mylar

### PR DESCRIPTION
**Pull request by phenonymous**

### CODE REVIEW

**Comment by nemchik** [comment]
This looks good to me but we've realized Travis tests won't pass because this is a PR from a fork which means our github token is prevented from being included in the build, and that causes the whole thing to fail. I'm going to work on getting this fixed today so we can properly build this PR and get it merged. Hang tight.

**Comment by nemchik** [comment]
I believe I have the issue resolved. Once we see travis pass this we'll review for merge.

**Comment by nemchik** [comment]
If this is approved I will merge with squash to clean up the commit history.

**Comment by nemchik** [comment]
Well done @phenonymous thanks for submitting this! Feel free to submit more if you have them. This page https://github.com/GhostWriters/DockSTARTer/wiki/Potential-Future-Apps is kind of a wishlist of sorts.

**Comment by phenonymous** [comment]
No problem :smile:  Sure will do. I'm already in progress of adding grafana before I looked at the list. Specifically this: https://github.com/matisku/tig-stack . It's default configuration is to monitor docker apps,  looking in to how to monitor the host system. It's a stack as a service so I'm not sure what's the best approach for that is. Grafana by it self doesn't do much but to visualize data.

I added portainer agent on my fork which is not on your list. It's a container that connects to the docker socket which allows multiple portainer endpoints to talk. It's useful if you have more than one server running portainer or, like me, running lxd or some other vm.
It might not be for your general use case so I'm not sure if I should do a pull request on that or not. Let me know

**Comment by phenonymous** [comment]
Also I have expirence with doing minimal docker images so if there something that you'd like to be added but has no docker image, let me know :smile:

**Comment by nemchik** [comment]
That all sounds amazing!

Does Portainer Agent require you to make modifications to your system like this? https://github.com/GhostWriters/DockSTARTer/commit/9c823324ca6adc653dff7a8da687602cd37878d3 Specifically that accomplishes the changes mentioned here https://stackoverflow.com/a/43539359/1384186

**Comment by phenonymous** [comment]
No, it works out of the box. You just have to deploy the container and hook it up on your main portainer. 
I use to do it the way mentioned in your link but it got tiredsome after having to do it on all my lxd containers. 

It's the makers of Portainer who maintains the agent, read more here https://portainer.readthedocs.io/en/stable/agent.html

**Comment by nemchik** [comment]
That sounds a lot nicer than the method I was trying to create. Would you mind making a PR for that?

As for other apps, we're not limited to only the ones on our potential future list, if there's something you want in DS feel free to PR it, or join us on Gitter https://gitter.im/GhostWriters/DockSTARTer and we can chat about it if you're not sure if it's worth adding.

**Pull request merged**
