### PR TITLE
Omadacontroller ports

### PR DESCRIPTION
**Pull request by mcaron1234**
# Pull request

**Purpose**
Omadacontroller was missing the ports.yml file. I added this file and updated the labels.yml file.

**Approach**
How does this change address the problem?

The controller can now be accessed via web browser or app.

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

This addresses the bug reported in [issue 1582](https://github.com/GhostWriters/DockSTARTer/issues/1582)

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by nemchik — CHANGES_REQUESTED** [review]
Good catch on the missing ports file (surprised we didn't catch that sooner). Looking at the labels/vars now I actually think we should get this to conform to the labels/vars used everywhere else: `appname_port_####` ex: `omadacontroller_port_8043` (basically without the extra description being part of the label/var).

**Comment by mcaron1234** [comment]
Should be good now.

**Comment by nemchik** [comment]
> Should be good now.

I think this also needs to be adjusted https://github.com/GhostWriters/DockSTARTer/blob/2f7927ad44ac6a1044b0591e93be590f46b49a32/compose/.apps/omadacontroller/omadacontroller.yml#L5-L9 to use the new variables.

**Comment by mcaron1234** [comment]
I hadn't even looked at that file, opps. I went over everything again, I think I caught them all this time.

**Review by nemchik — APPROVED** [review]

**Pull request merged**
