### PR TITLE
Switch to Airsonic-Advanced

### PR DESCRIPTION
**Pull request by nemchik**
# Pull request

**Purpose**
This closes https://github.com/GhostWriters/DockSTARTer/issues/1448

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by shahvirb** [comment]
@nemchik I have mixed feelings about this approach of just updating the image to "-advanced"

https://github.com/linuxserver/docker-airsonic-advanced#application-setup says "We don't formally support upgrading from Airsonic to Airsonic Advanced, it may or may not work for you and we'd recommend making backups before attempting this."

I think the safer approach would be to create a new "airsonic-advanced" app and we mark the "airsonic" app as deprecated.

**Comment by CLHatch** [comment]
> @nemchik I have mixed feelings about this approach of just updating the image to "-advanced"
> 
> https://github.com/linuxserver/docker-airsonic-advanced#application-setup says "We don't formally support upgrading from Airsonic to Airsonic Advanced, it may or may not work for you and we'd recommend making backups before attempting this."
> 
> I think the safer approach would be to create a new "airsonic-advanced" app and we mark the "airsonic" app as deprecated.

Doing it that way, if someone wanted to try to transfer their old setup over to the "advanced" one, they could just rename their `~/.config/appdata/airsonic` folder to `~/.config/appdata/airsonnic-advanced` anyways, knowing that it MIGHT not work (I'm just assuming those are the folder names, not looked).

**Comment by shahvirb** [comment]
Yes indeed. I think this is the safer approach but obviously less
convenient for users as a simple ds -u won't just update their app to the
advanced image.

Given that airsonics position is "proceed at your own risk" I nominate that
we respect this and don't force upgrade our users.

**Comment by nemchik** [comment]
I can appreciate all of that. In that case, I think reopening https://github.com/GhostWriters/DockSTARTer/pull/1453 makes more sense. The reason I went this direction was to avoid deprecation of the current image just to make things easier on users, but if the safer approach is to deprecate and make users migrate I'm fine with that. We should cover it in the docs.

**Pull request closed without merging**
