### PR TITLE
Switch to LSIO Plex (again)

### PR DESCRIPTION
**Pull request by nemchik**
## Purpose

`plexinc/pms-docker` seems to lag behind `linuxserver/plex` with updates and features now that LSIO is building images on their new pipeline. LSIO also includes ARM CPU support.

## Approach

Switch the image used for x86_64, add the ARM images, and adjust the environment variables. Existing users should not notice a difference unless they are currently set to use the "beta" releases in their plex settings (in the web ui). The default here will use the latest public release. Plexpass beta releases can be used by adjusting the `PLEX_VERSION` variable (see LSIO documentation).

#### Open Questions and Pre-Merge TODOs

- [x] #708 needs to be sorted first!
- [ ] Adjust our documentation https://dockstarter.com/apps/plex/ to remove references to the Plex Claim Token process and only recommend the host mode method.

#### Learning

https://hub.docker.com/r/linuxserver/plex

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by nemchik** [comment]
Tagging @mattgphoto would you mind testing this out (`ds -u origin/lsio-plex`) and setting up a PR to adjust the documentation?

**Comment by nemchik** [comment]
#708 needs to be resolved first! We cannot require users to use `host` network mode currently due to the `hostname` conflict.

**Comment by nemchik** [comment]
#708 is now resolved

**Comment by mattgphoto** [comment]
Documentation PR was completed as well: [#711](https://github.com/GhostWriters/DockSTARTer/pull/711)

**Pull request merged**
