### PR TITLE
docs: remove missing sickrage.md nav

### PR DESCRIPTION
**Pull request by setchy**
Removing `apps/sickrage.md` which doesn't exist, is rendering as `None` and has a redirect rule setup to `apps/sickchill`

### CODE REVIEW

**Comment by setchy** [comment]
@nemchik - would you be so kind as to review this PR when you get a moment. Thanks!

**Comment by angrycuban13** [comment]
@setchy this is happening on another pull request. I'm waiting on @nemchik to look at it.

**Comment by setchy** [comment]
thanks @angrycuban13 - i've added a `.ecrc` file to skip linting the github workspace `.git` folder - with success.  

re the `no such manifest: docker.io/adguard/adguardhome:latest` error - 🤷‍♂️

**Comment by nemchik** [comment]
> 

Fixed in https://github.com/GhostWriters/DockSTARTer/commit/c370f458e8593bb43236c8a26494a1a35f7d2901

Git started caring about the user that runs `git` commands. editorconfig-checker uses git to determine which files to check, but when it can't it falls back on finding all files. When it finds all files, it includes files in the `.git` folder, which don't match the `.editorconfig` rules. Running as the user (instead of as root) fixes the issue.

**Review by nemchik — APPROVED** [review]

**Pull request merged**
