### PR TITLE
Add menu to prompt for app vars

### LINKED ISSUE #186: Individual App Settings
preview

`whiptail --yesno "$(grep 'PLEX_' ~/.docker/compose/.env)" 0 0`

```
while IFS= read -r line; do
    SET_VAR=${line/=*/}
    SET_VAL=${line/*=/}
    echo
    echo "SET_VAR = ${SET_VAR}"
    echo "SET_VAL = ${SET_VAL}"
    echo
done < <(grep "${APPNAME}_" ~/.docker/compose/.env)
```

### LINKED ISSUE #270: Permissions
**Describe the bug**
I have started using Duplicati for backing up my system and it can only see files under the dockershared directory. At first I had it set to my home folder /home/user but then I wanted to backup other folders so I changed the dockershared directory to / just to included everything. Then I realized the permissions would not allow me to backup what I wanted to. Without thinking very much about it I re-ran configure apps and said yes to set permissions to the dockershared folder (/)  This most obviously ruined my entire ubuntu installation as now essentially all permissions were set to my user.  Maybe a warning or actually not allowing someone to set permissions for certain folders.

**To Reproduce**
1. Set dockershared folder to /
2. Answer Yes to set permissions in dockershared folder
3. All permissions are now borked.

**Expected behavior**
To not so easily ruin the entire OS with a few clicks and no warnings.

**System (please complete the following information):**
 - OS: Ubuntu 18

**Additional context**
- I have files I would like to back up outside of my user folder and might not be owned by my user.

### PR DESCRIPTION
**Pull request by nemchik**
## Purpose
This closes #186 
This closes #270 

## Approach
- Add a function file `menu_app_vars` to prompt for all vars related to an app.
- If there are no vars to config let the user know (gently).
- Default to keep existing, the user can select `No` to change.
- Run this prompt for each selected app during the app select menu.
- Add some minor improvements to the value prompt script such as a space between the option and value.
- Add descriptions to all types of value prompts.
- Prevent `set_permissions` from running on specific locations.

#### Open Questions and Pre-Merge TODOs
- [x] Do a lot of testing
- [x] Do more testing

## Requirements
- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by nemchik** [comment]
This will also close #270

**Comment by robertbaker** [comment]
Does this change the behavior of ds -g? I would like to skip all the path vars and permissions prompts without going No No No No...

**Comment by nemchik** [comment]
This does not change the behavior of `-g`.

I'm actually considering splitting up the main menu a bit more to something like
- config apps + vars + globals
- config apps
- config vars
- config globals
- rest of the current menu

I might put all of the config stuff into a sub menu.

Anyway -g will always be as short as possible. By the time you figure out how to use -g you probably don't need the menu anymore lol.

**Comment by robertbaker** [comment]
I use -g to make updates, I'm guessing there's a arg to add an app.

I like your proposal, however I suggest:

Add/Remove apps or Enable/Disable apps instead of Configure apps

**Comment by nemchik** [comment]
-g stands for generate. It generates the docker-compose.yml file that's used to run your docker apps. If you change your .env you have to rerun -g for the changes to affect your apps.

-u is to update DockSTARTer to the latest changes from here. 

There's currently no way to just select apps without going through the menu or editing your .env file directly. In the .env file you can enable apps by changing for example SONARR_ENABLED to true (for whatever app you want) then rerun -g

**Pull request merged**
