### PR TITLE
Added timemachine; fixes #1344

### LINKED ISSUE #1344: [Application Request] Time Machine
# Name of the application
Time Machine

## GitHub
https://github.com/mbentley/docker-timemachine

## Docker Hub/GitHub Registry
https://hub.docker.com/r/mbentley/timemachine

### Additional context
It would be awesome to add time machine to the app list, to be able to backup Mac computers using Time Machine

### PR DESCRIPTION
**Pull request by mbentley**
Signed-off-by: Matt Bentley <mbentley@mbentley.net>

# Pull request

**Purpose**
Closes #1344 

**Approach**
Adds `mbentley/timemachine`

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by mbentley** [comment]
Example compose file in my repo if validation needs to be done against the default environment variables/labels: https://github.com/mbentley/docker-timemachine/blob/master/timemachine-compose-smb.yml

**Comment by nemchik** [comment]
Thanks for the PR! I have a couple of questions/requests.

I think it makes sense to allow the data directory to be user configurable. An app that is already in DS that does this (can be referenced as an example) is https://github.com/GhostWriters/DockSTARTer/tree/master/compose/.apps/nextcloud

For the UID/GID, would it make sense to set this to use the global `PUIG` and `PGID` variables that DS has available? These are normally detected and set by DS to be the user who runs DS (typically `1000` on ubuntu). I could see it being important to set another user in some cases, but this could also be accomplished with an override. I would guess that most users who might run this container would have any files in the data directory owned and accessible by the user that runs DS.

**Comment by mbentley** [comment]
Sure thing; let me update the PR.  For persistent data, are there any specific mount points that are common for persistent data that isn't configuration related?  I see nextcloud used `/mnt/nextcloud`.  I can make `PUID` and `PGID` have the same effect as the `TM_UID` and `TM_GID` variables via https://github.com/mbentley/docker-timemachine/commit/c2dcffeaf5332f30af85053b17787dac3fb40c54 so that's easy enough to just use those since they're standard in DS.  Updated images will be published later - dealing with an unexpected power outage at the moment.

**Comment by nemchik** [comment]
> For persistent data, are there any specific mount points that are common for persistent data that isn't configuration related?

Generally there's `${DOCKERCONFDIR}/<appname>:/container/config/path` for configuration data and `${DOCKERSTORAGEDIR}:/storage` (always the same on all containers) for a shared storage location. Shared storage is often used for things like downloads or media library by creating subfolders beneath it. A benefit of shared storage is usually atomic moves and hardlinks.

Aside from that, app specific data that needs to be located at a specific path inside the container are usually configured as separate volumes (ex: nextcloud). This includes data that might not be appropriate to be shared between apps (ex: sensitive files).

> I can make `PUID` and `PGID` have the same effect as the `TM_UID` and `TM_GID` variables via [mbentley/docker-timemachine@c2dcffe](https://github.com/mbentley/docker-timemachine/commit/c2dcffeaf5332f30af85053b17787dac3fb40c54) so that's easy enough to just use those since they're standard in DS. Updated images will be published later - dealing with an unexpected power outage at the moment.

I think it could be as simple as changing:
```yaml
- TM_GID=${TIMEMACHINE_TM_GID}
- TM_UID=${TIMEMACHINE_TM_UID}
```
to

```yaml
- TM_GID=${PGID}
- TM_UID=${PUID}
```
in the compose template for the PR and removing the labels that wouldn't be needed. If you meant something else by your comment I may have misunderstood.

**Comment by mbentley** [comment]
Well I sure did overthink the PUID and GUID thing a bit but I suppose it still works either way 😆.  I know that I've had someone request using PUID and GUID on another image I've maintained.  I just pushed a new commit that I believe should address all of the requested updates.  If you'd like me to squash my commits, I'd be happy to do so.  Let me know if there are any other changes required.  Thanks for the quick response!

**Review by nemchik — APPROVED** [review]
LGTM! Thanks very much for adding!

**Pull request merged**
