### PR TITLE
Add Traefik App

### PR DESCRIPTION
**Pull request by shahvirb**
# Pull request

**Purpose**
Adding support for [Traefik](https://hub.docker.com/_/traefik)

**Approach**
Followed contributing.md for adding new app

**Open Questions and Pre-Merge TODOs**
- [x] I'm open to suggestions on the volume mapping `${DOCKERCONFDIR}/traefik/traefik.yml:/etc/traefik/traefik.yml` VS using  an environment variable to locate this traefik.yml file

**Testing**
1. ds -a traefik
2. Created traefik.yml with basic contents
```
## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# API and dashboard configuration
api:
  insecure: true
```
3. Visited <host>:8080 and to ensure I can see the Traefik dashboard

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by shahvirb** [comment]
Unsure of our repo policy for squashing commits. Is the responsibility on me as the author to squash or will you squash and merge when you approve this PR?

**Comment by nemchik** [comment]
> Unsure of our repo policy for squashing commits. Is the responsibility on me as the author to squash or will you squash and merge when you approve this PR?

I'm not too concerned with squashing.

**Comment by nemchik** [comment]
Are there files that exist inside the container at `/etc/traefik/` other than `traefik.yml`?

**Comment by shahvirb** [comment]
> Are there files that exist inside the container at `/etc/traefik/` other than `traefik.yml`?

By default no.

Note that this config file can be located elsewhere, either in one of the four search directories or in a custom location
https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file

**Comment by nemchik** [comment]
> > Are there files that exist inside the container at `/etc/traefik/` other than `traefik.yml`?
> 
> By default no.
> 
> Note that this config file can be located elsewhere, either in one of the four search directories or in a custom location https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file

could we do `${DOCKERCONFDIR}/traefik:/etc/traefik` ?

**Comment by shahvirb** [comment]
@nemchik I'm sure you're busy. Whenever you have a moment just a gentle nudge on this PR. Thanks!

**Review by nemchik — APPROVED** [review]
LGTM

**Pull request merged**
