### PR TITLE
Cleanup

### LINKED ISSUE #667: appdata Documentation
Replacing https://github.com/GhostWriters/DockSTARTer-wiki/issues/9

All references to `~/.docker/config` need to be replaced with `~/.config/appdata` in all documentation.

### LINKED ISSUE #668: Cleanup Documentation
Now that we have the https://github.com/GhostWriters/DockSTARTer/tree/docs branch we need to cleanup the existing documentation (mainly https://github.com/GhostWriters/DockSTARTer/blob/master/README.md and some of the files in the docs branch) to only reference https://dockstarter.com/ as it contains all the wiki documentation. We might also be able to adjust the wiki contributor badge to use the docs branch.

### PR DESCRIPTION
**Pull request by nemchik**
## Purpose

Lots of documentation cleanup.
This closes #668 
This closes #667 

## Approach

Update config locations to appdata. Use subfolders to categorize pages into three main categories (basics/advanced/apps). Use lowercase file names everywhere (will keep URLs cleaner). All app page file names must match the name in the main DS repo. Add code highlighting in a lot of places.

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by nemchik** [comment]
This is a solid start, but there's still a bit of outdated info on some pages. Some pages maybe should be moved between basic and advanced.

**Comment by nemchik** [comment]
I tested this locally but certainly wouldn't hurt if a second set of eyes had a look and let me know if there's anything else glaring that should be considered low hanging fruit and fixed with this PR.

to test locally I would recommend cloning the repo to a separate folder (NOT your actual DS install folder) and checkout the `docs-cleanup` branch and then run `mkdocs serve` assuming  you have mkdocs and mkdocs-material installed. if not you can use `docker run -it --rm -v ${PWD}/site:/site -v ${PWD}:/docs squidfunk/mkdocs-material serve`

**Comment by nemchik** [comment]
Updated to included merged BitWarden page.

**Comment by mattgphoto** [comment]
I tried this out on a new ubuntu vm just for kicks, and didn't have any luck being able to reach the service at all:
```
matt@ubuntu:~/.docker$ docker run -it --rm -v ${PWD}/site:/site -v ${PWD}:/docs squidfunk/mkdocs-material serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
[I 190504 02:15:55 server:298] Serving on http://127.0.0.1:8000
[I 190504 02:15:55 handlers:59] Start watching changes
[I 190504 02:15:55 handlers:61] Start detecting changes
```
With a curl/wget result of from the same box:
```
matt@ubuntu:~$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS              PORTS               NAMES
db5212db1f4c        squidfunk/mkdocs-material   "mkdocs serve"      5 seconds ago       Up 5 seconds        8000/tcp            compassionate_pike
matt@ubuntu:~$ wget http://127.0.0.1:8000
--2019-05-03 19:16:15--  http://127.0.0.1:8000/
Connecting to 127.0.0.1:8000... failed: Connection refused.
matt@ubuntu:~$ curl http://127.0.0.1:8000
curl: (7) Failed to connect to 127.0.0.1 port 8000: Connection refused
matt@ubuntu:~$

**Comment by nemchik** [comment]
I'm going to merge this. There's still some things that need to be addressed but it's smaller things that can be individual PRs such as fixing a few broken links.

**Pull request merged**
