### PR TITLE
Adding arguments for advanced usage

### PR DESCRIPTION
**Pull request by MagicalCodeMonkey**
**Purpose**
Add advanced command line arguments, primarily for script usage like DSAC

**Approach**
Currently, DSAC uses modified versions of env_set, env_get, and yml_get which is prone to issues if changes occur. Making these available will allow for DSAC and other scripts to use the DS version of env_set, env_get, and yml_get.

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by nemchik** [comment]
I'm ok with this being added. I don't know what's going on with the linters. I haven't dug in for a full review, but I think we talked about it on discord. I'll have to double check.

**Comment by MagicalCodeMonkey** [comment]
Re-opening to get it up-to-date, etc.

**Comment by MagicalCodeMonkey** [comment]
If this is still good, can you merge it, @nemchik ?

**Comment by nemchik** [comment]
Sorry I need to look at this.

**Pull request merged**
