### PR TITLE
Updating XBackBone to LSIO

### PR DESCRIPTION
**Pull request by angrycuban13**
# Pull request

**Purpose**
Updates DS to use LSIO for XBackBone

### CODE REVIEW

**Comment by angrycuban13** [comment]
It is a draft until I get with Gil about the environment variables
```yml
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - PHP_POST_MAX_SIZE=1024M
```

**Comment by angrycuban13** [comment]
Environment variables are not supported. A file must be modified. Announcement made in DS. Ready for review @nemchik

**Comment by angrycuban13** [comment]
Not stale

**Review by nemchik — APPROVED** [review]

**Comment by nemchik** [comment]
Sorry for not getting to this sooner

**Pull request merged**
