### PR TITLE
Add all the optional parameters for the speedtest service

### PR DESCRIPTION
**Pull request by dylanmtaylor**
# Pull request

**Purpose**
While in there fixing it, might as well add the optional parameters too

**Approach**
Added all params from https://github.com/henrywhitaker3/Speedtest-Tracker#parameters

- [X] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [X] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by angrycuban13** [comment]
These can all be enabled on the web UI which is why they hadn't been added.

**Comment by nemchik** [comment]
Fair enough. The web UI should hopefully take precedence.

**Comment by angrycuban13** [comment]
I'm fine with either or just wanted to make sure you guys were aware henry had made it usable on the web ui

**Comment by dylanmtaylor** [comment]
I don't have authorization to merge it anyways, but I don't mind either way - didn't realize these were part of the web UI, just noticed they weren't there in the configuration when looking at the variables

**Pull request closed without merging**
