### PR TITLE
[WIP] Adds Wallabag

### LINKED ISSUE #438: Add Wallabag
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add Wallabag to DockStarter

**Describe alternatives you've considered**

**Additional context**
wallabag is a self hostable application for saving web pages. Unlike other services, wallabag is free (as in freedom) and open source.
With this application you will not miss content anymore. Click, save, read it when you want. It saves the content you select so that you can read it when you have time.
I think it would be a great addition to DockStarter.

Docker Official repo [here](https://github.com/wallabag/docker)

### PR DESCRIPTION
**Pull request by Zayon**
# This is a work in progress 

Use official wallabag docker image with the mariadb container (by
default).
See https://github.com/wallabag/docker
https://github.com/wallabag/wallabag/issues/3662

## Purpose

Add the Wallabag application

Fixes #438 

## Approach

Adds the required yaml files

#### Open Questions and Pre-Merge TODOs

- [ ] Testing
- [ ] Add documentation on how to fix the db issues before wallabag 2.4
- [ ] Add documentation on how to import from existing wallabag instances or from other services (such as pocket for example) with a redis or a rabbitmq container (most likely redis)

#### Learning

The official wallabag docker image seems to have some bugs.

The database is not properly populated, it required manual intervention to make it work, see https://github.com/wallabag/wallabag/issues/3662

These should be fixed when wallabag 2.4 will be released.

This pull request required some more testing and at least some documentation on troubleshooting the database setup

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by rob151515** [comment]
Just looking at this because I'm keen to implement Wallabag myself and noticed that you seem to be mapping the freshrss config dir when mapping volumes:

${DOCKERCONFDIR}/freshrss:/config

Possibly a typo?

**Comment by Zayon** [comment]
Yes, bad copy/paste sorry

**Comment by Zayon** [comment]
I managed to add wallabag to my dockstarter instance through `docker-compose.override.yml` and have imported articles from my previous instance with rabbitmq.

The official wallabag docker images have some bugs and I had to do a lot of debugging and manual interventions inside the container.

Some of the issues I have encountered are: 

- Database creation is buggy in last image, have to manually add a migration and play it manually
- Automatic database creation fail, had to use `POPULATE_DATABASE=false`.
- Rabbitmq parameters can't be passed as environment variables, I had to manually edit the `parameters.yml` file inside the container.
- Could not mount the `parameters.yml` file in the host. The git clone command crash if the directory is not empty. This means the file must be edited through the container directly and cannot be backed-up.

So, I'm not sure it's possible to have it working "out of the box" with dockstarter for now :cry: Maybe wait for wallabag 2.4 and the updated docker image to have less issues.

**Comment by nemchik** [comment]
Sounds good. We can leave this open if you want. Stale Bot may try to close it after 2 months.

**Pull request closed without merging**
