### PR TITLE
Add compose template links to all app docs

### PR DESCRIPTION
**Pull request by nemchik**
# Pull request

**Purpose**
Link from our docs to the repo to easily access the compose templates. This should make it easier for users to see what DS is stitching together and whether there is an architecture specific file for the app.

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by angrycuban13 — CHANGES_REQUESTED** [review]
Missing:

- Deemix (GitLab)
- Duplicacy (GitHub Badge missing as well)


Fix: 

- Remove `mcmyadmin.md`
- Remove `sickrage.md`

One of your previous commits removed all deprecated apps, but looks like these 2 stayed behind. It was around the time they removed the redirect thing, when the `https://dockstarter.com/discord` wouldn't redirect correctly.

**Comment by angrycuban13** [comment]
Actually, I know why Duplicacy is missing the GitHub page. The container uses BitBucket and I couldn't figure out the badge.

Do we want to link the upstream GitHub page in this case? I can easily push into a new PR that since I have it staged locally.

**Comment by nemchik** [comment]
We can do a custom badge and link to the bitbucket repo so that we're linking to the image source. All the badges in this pr are custom static badges (as opposed to dynamic badges that show numbers or statuses).

**Comment by angrycuban13** [comment]
I couldn't figure out Bitbucket lol

**Pull request merged**
