### PR TITLE
Added xTeVe & xTeVe Documentation

### LINKED ISSUE #1001: xTeve v2 - Useful and not Buggy anymore
# Feature request

**Is your feature request related to a problem? Please describe.**
No; love DockSTARTer and have been using it for a while now.

**Describe the solution you'd like**
xTeve - https://hub.docker.com/r/dnsforge/xteve

**Describe alternatives you've considered**
I tried all over DVR/IPTV integrations and xTeve v2 actually has a solid foundation now

**Additional context**
Thanks.

### PR DESCRIPTION
**Pull request by angrycuban13**
# Pull request

**Purpose**
Closes #1001 

**Approach**
How does this change address the problem?

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by nemchik** [comment]
Closes #1001

In the body of the PR, not the title.

**Comment by angrycuban13** [comment]
> 
> 
> Closes #1001
> 
> In the body of the PR, not the title.

When will I learn....

**Comment by islanddog** [comment]
I am patiently waiting on this and thanks all for getting this integrated. Currently running it as a Windows service on my work machine to my docker. It integrates perfectly into Emby with my IPTV Service.

**Comment by islanddog** [comment]
I know this is closed but it does reference xTeve. I would like to use Cloudflare DDNS to manage xTeve remotely. I have been using Organizr for other associated applications. Does someone know a nginx/proxy-confs that I can reference to get it running? Thanks.

**Comment by angrycuban13** [comment]
@islanddog you might want to check their repo or documentation to see if they have an nginx reverse proxy example.

**Pull request merged**
