### PR TITLE
Jdownloader2

### PR DESCRIPTION
**Pull request by karl0ss**
Working PR to enabled JDownloader2 in DOCKstart

- Port 5800 is used to access the JDownloader GUI via http://<SERVERIP>:5800
- Port 3129 is used for the myJdownloader client to connect.

- /download is using the ${DOWNLOADSDIR}, this needs to be set in jdownloader settings once 
container is running via http://<SERVERIP>:5800, I can add a wiki entry for this
- /config is pointing to the standard ${DOCKERCONFDIR}/jdownloader2

### CODE REVIEW

**Comment by nemchik** [comment]
This looks good. I'm going to retry the travis builds to see if I can get them to pass (travis is weird about passing PRs because of github API limits)

**Comment by karl0ss** [comment]
No problem, I just pulled my branch with this and my LogitechMediaServer PR and both are showing and installing as expected..

**Comment by nemchik** [comment]
Can we keep this called `jdownloader2` rather than `jdownloader2_gui` for simplicity? (does that still accurately represent the name of the app?)

**Comment by nemchik** [comment]
Reference #442 #410

**Comment by karl0ss** [comment]
I have updated the app as I have now also created the multiarch version that was spoken about in the app request, and called that _nogui, there is a pr for both.

**Comment by nemchik** [comment]
I feel like having two separate jdownloader2 images is a bit confusing and I think it would be best if we could find one image to use that offers the most to us.

My (loosely defined) preferred ranking of images would be:
1. Official image from the dev of the app contained inside the image
2. Image published by a well known reputable source like LSIO/binhex/oznu/hotio
3. The most popular available image on docker hub that offers support for multiple architectures and is up to date (updated at least as often as the app inside the container)
4. The easiest to use image available from docker hub that otherwise meets all the criteria of the point above with the exception that it might not be the most popular but instead offers legitimate and valid ease of use improvements or is better maintained (more recently updated or kept up to date with the app contained in the image)

I'll see if we can locate such an image and post it in the relevant issues/PRs and maybe we can just stick to one. If I'm missing something and there's a valid reason for these to be two separate images (ex: deluge without a vpn and deluge with a vpn) please let me know.

**Comment by nemchik** [comment]
I'm sure something like this would be possible. I'll ask some friends what their thoughts on it are, and will see if we can locate an already existing candidate that meets all the needs.

**Pull request closed without merging**
