### PR TITLE
Initial samba support using dperson/samba

### PR DESCRIPTION
**Pull request by jeliasson**
## Purpose

Make media directories accessible over Samba (SMB). This would allow for example Windows users to mount to a drive or a network path. 

## Approach

Using `dperson/samba` docker image, expose `MEDIADIR_*` environments variables and mount them in the Samba image and have them accessible over SMB, e.g. `\\server\Books`. Shares would be protected using static username and password defined in `.env`.

### Open Questions and Pre-Merge TODOs
- [X] Documentation
- [X] Test
- [X] Define static username and password (`DockSTARTer`/`DockSTARTer`)

## Requirements

- [X] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [X] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by nemchik** [comment]
I pushed a few small tweaks and merged the latest changes from master. Travis is testing it now, we'll need the full generator test to pass (Stage 2.4 under https://github.com/GhostWriters/DockSTARTer/pull/419/checks ) This phase is normally allowed to fail so that builds can pass when all of the other checks pass because the .4 build usually takes 20+ minutes.

**Comment by jeliasson** [comment]
As we're trying to bind ports below `=<1024`, do we need to consider any permissions from a build and a runtime perspective?

**Comment by nemchik** [comment]
Not specifically. The documentation on ports says that as long as they are in quotes it's not an issue. The `yq` binary we use actually strips the quotes anyway, but i've not seen it cause an issue yet. We've got a few apps that use ports like 80 and 53.

**Comment by jeliasson** [comment]
@nemchik Please rebuild 2.4.

**Comment by nemchik** [comment]
FYI this branch has your changes thus far. https://github.com/GhostWriters/DockSTARTer/tree/feature/samba-docker-app

I'll keep pulling your changes to that branch so that Travis will test properly and we'll merge this PR once:
1. You're satisfied with the testing
2. I'm in agreement with the PR
3. Travis passes on all builds including stage 2.4

Ping my anytime for the branch to be updated since Travis doesn't like to build PRs.

**Comment by jeliasson** [comment]
In the final progress of migrating my 2 TB Bitlocker volume to ext4, so I've soon catched up to have this PR sorted 👍

**Comment by jeliasson** [comment]
Adding documentation [on the wiki](https://github.com/GhostWriters/DockSTARTer/wiki/Samba).

**Comment by jeliasson** [comment]
I think we're good @nemchik.

**Pull request merged**
