### PR TITLE
Jdownloader

### PR DESCRIPTION
**Pull request by karl0ss**
This is my implementation of jdownloader2 in our DockSTARTer,

This works on my install, and I have copied how other apps have appeared to be added to the system, but this doesn't appear to allow my app to be installed? its not present on the list...

Any help would be good please

### CODE REVIEW

**Comment by nemchik** [comment]
I'll be able to have a look at this next week and we'll make some changes to get it working

**Comment by nemchik** [comment]
This was looking good, feel free to continue with it and ask if you need anything.

**Comment by karl0ss** [comment]
I have made a new repo as I broke something and it was easiest to start again, I have created a pr for LogitechMediaServer, having made it the same way I did this, that works...but this just doesn't display in the list of applications to install

**Comment by nemchik** [comment]
`JDOWNLOADER_ENABLED` and other env vars should be `JDOWNLOADER2_ENABLED` (with the `2`). That'll get it to show in the menu.

**Pull request closed without merging**
