### PR TITLE
Add FileBot

### LINKED ISSUE #557: Add Docker FileBot
Is your feature request related to a problem? Please describe.
No

Describe the solution you'd like
FileBot is the ultimate tool for organizing and renaming your movies, tv shows or anime, and music well as downloading subtitles and artwork. This is a docker image containing both the current FileBot as well as an older version of the image that has the Donation supported version available. Image has a GUI and very good documentation provided on the compose file and other features/functionality.

https://github.com/jlesage/docker-filebot

https://hub.docker.com/r/jlesage/filebot

Describe alternatives you've considered
Installing it manually

Additional context
None

### PR DESCRIPTION
**Pull request by nemchik**
## Purpose

This closes #557 

## Approach

Add the required files.

#### Open Questions and Pre-Merge TODOs

- [ ] Testing:
```bash
ds -u origin/filebot
ds -a filebot
```

#### Learning

https://github.com/jlesage/docker-filebot
https://hub.docker.com/r/jlesage/filebot

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by Killianbe** [comment]
That error appear :  
Creating filebot ... error                                                                                              
ERROR: for filebot  Cannot create container for service filebot: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for filebot  Cannot create container for service filebot: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
2019-08-02 01:48:03 [FATAL ]   Docker Compose failed.
2019-08-02 01:48:03 [ERROR ]   DockSTARTer did not finish running successfully.

**Comment by nemchik** [comment]
I've updated the branch, can you try the testing commands again?

That error means one of your variables that is supposed to have a variable in it is empty. You may want to check your `.env` file. I have plans for the future to add additional validations for variables.

**Comment by Killianbe** [comment]
`WARNING: The FILEBOT_OUTPUTDIR variable is not set. Defaulting to a blank string.
WARNING: The FILEBOT_WATCHDIR variable is not set. Defaulting to a blank string.
Pulling filebot (jlesage/filebot:)...
latest: Pulling from jlesage/filebot
bdf0201b3a05: Pull complete
8cc9a1077820: Pull complete
4aa38d8d28d5: Pull complete
751b290f0b1e: Pull complete
fba191c444bf: Pull complete
236ad55fd859: Pull complete
7240b24290d9: Pull complete
df081ed66f0a: Pull complete
50634628aeb1: Pull complete
6dff2dedcc24: Pull complete
b0f5976b8605: Pull complete
e30bcce2ffa7: Pull complete
ce7ea4424937: Pull complete
3f068b1f4319: Pull complete
2c9e408c6b37: Pull complete
4e71803c24b3: Pull complete
103b8288dc51: Pull complete
a663f375b5b6: Pull complete
c50cb843fa40: Pull complete
d0cdeebc2ee2: Pull complete
53986aed67ad: Pull complete
Digest: sha256:93edb05f36a41bcf4cf3ffaa0d3d794ca1a4585f64005314b9ec392de41fa7fd
Status: Downloaded newer image for jlesage/filebot:latest
organizr is up-to-date
portainer is up-to-date
lidarr is up-to-date
letsencrypt is up-to-date
Recreating jackett ...
qbittorrent is up-to-date
ttrss is up-to-date
ombi is up-to-date
nextcloud is up-to-date
netdata is up-to-date
couchpotato is up-to-date
ouroboros is up-to-date
sonarr is up-to-date
monitorr is up-to-date
Recreating emby    ...
Creating filebot   ... error
Recreating jackett ... done
Recreating emby    ... done
 names should be at least two alphanumeric characters

ERROR: for filebot  Cannot create container for service filebot: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
2019-08-06 15:13:55 [FATAL ]   Docker Compose failed.
2019-08-06 15:13:55 [ERROR ]   DockSTARTer did not finish running successfully.`

It's the same, DS don't give me choice to add variable (OUTPUT & WATCHDIR)

**Comment by nemchik** [comment]
Found the issue (pretty sure). fixed it. sorry. I added the wrong variable name.

**Comment by mouzzampk2014** [comment]
So far working very stable

**Comment by nemchik** [comment]
Thanks. I'll merge once the build tests complete.

**Pull request merged**
